language : go 

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
  - pip install --user awscli
install:
  - go get github.com/constabulary/gb/...
  - sudo apt-add-repository ppa:duggan/jo --yes
  - sudo apt-get update -q
  - sudo apt-get install jo
  - go get -u github.com/tools/godep/...
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling.git
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling
  - godep restore
  - go install ./...
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-recipes.git
  - git clone -b buildflag https://github.com/LakshmiMekala/recip1.git
  - pushd recip1/samples-recipes
  - rm -rf master-builds 
  - mkdir -p master-builds/latest/temp builds/latest
  
script:
   - chmod ugo+x ./buildflag.sh
   - ./buildflag.sh OPTIMIZE=TRUE
   - popd
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
  - "[ -f \"${HOME}/.aws\" ] && rm -f ${HOME}/.aws"
deploy:
  provider: s3
  access_key_id: $SITE_KEY
  secret_access_key: $SITE_KEY_SECRET
  bucket: $AWS_BUCKET
  region: $AWS_REGION
  skip_cleanup: true
  on:
    all_branches: true
  local_dir: $GOPATH/src/github.com/TIBCOSoftware/recip1/samples-recipes/master-builds
  upload-dir: master-builds
  
