language : go 

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
  - go get github.com/constabulary/gb/...
  - go get -u github.com/constabulary/gb/...
  - go get github.com/TIBCOSoftware/mashling/...
#  - pwd
  - cd ../../TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-recipes.git
  - git clone -b bincheck https://github.com/LakshmiMekala/recip1.git
  - pushd recip1/samples-recipes
  - mkdir -p master-builds/latest #builds/latest
  - ls
  
script:
   - chmod ugo+x ./f19.sh
   - ./f19.sh
   - popd
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"