language : 
  - go  
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
 
os: 
  - linux
  - osx
#  - windows

install:
   - go get github.com/constabulary/gb/...
   - go get -u github.com/constabulary/gb/...
   - echo $TRAVIS_BUILD_ID
   - echo $TRAVIS_BUILD_NUMBER
   - echo $TRAVIS_JOB_ID
   - echo $TRAVIS_JOB_NUMBER
   - echo $TRAVIS_REPO_SLUG
   - echo $TRAVIS_COMMIT
   - echo $TRAVIS_TAG
   - mkdir -p "$TRAVIS_REPO_SLUG-$TRAVIS_BUILD_NUMBER"
   - cd "$TRAVIS_REPO_SLUG-$TRAVIS_BUILD_NUMBER"
   - pwd
#  - go get github.com/TIBCOSoftware/flogo-cli/...
#  - go get -u github.com/TIBCOSoftware/flogo-cli/...
#  - go get github.com/TIBCOSoftware/mashling-cli/...
#  - go get -u github.com/TIBCOSoftware/mashling-cli/...
#  - pwd
#  - cd ../../TIBCOSoftware
#  - git clone https://github.com/LakshmiMekala/recip1.git
#  - cd recip1
#  - git clone recipe https://github.com/LakshmiMekala/recip1.git
#  - git checkout -b recipe origin/recipe
#  - pushd samples-recipes
#  - ls
#script:
   - go get github.com/TIBCOSoftware/flogo-cli/...
#   - chmod ugo+x ./build-c-new.sh 
#   - ./build-c-new.sh
#   - popd

after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc" 

