sudo: required
language : 
  - go  

services:
  - docker

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
  - go get -u github.com/constabulary/gb/...
  - go get -u github.com/tools/godep/... 
  
  
script:
  - mkdir -p $GOPATH/src/github.com/TIBCOSoftware
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - git clone https://github.com/TIBCOSoftware/mashling.git
  - cd mashling
  - godep restore
  - go test ./...
  - go install ./...
  - mashling version  
  -  pushd mashling-cicd/docker/mashling;
  -  chmod ugo+x ./build-mashling.sh
  -  ./build-mashling.sh 
  -  popd
    
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"

after_success:
  - "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\" tibdocker.tibco.com"
  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" || -n ${TRAVIS_TAG} ]; then
    source $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/scripts/init.sh ;
    mashling::module::postbuild mashling mashling ;
    fi" 
