language : 
  - go  
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc" 
os: 
  - linux
#  - osx
#  - windows
branches:
  only:
    - master
install:
  - go get github.com/constabulary/gb/...
  - go get -u github.com/constabulary/gb/...
  - go get github.com/TIBCOSoftware/mashling/...
  - pwd
  - cd ../../TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-recipes.git
  - git clone https://github.com/LakshmiMekala/recip1.git
  - pushd recip1/samples-recipes
  - mkdir -p master`-builds/latest
  - ls
  
script:
   - chmod ugo+x ./build-recipes.sh  ./build.sh ./recipe.sh ./rec.sh ./rec1.sh ./rec2.sh ./build-c-new.sh
#   - ./build-c-new.sh
#   - ./build-recipes.sh
#   - chmod ugo+x ./build.sh 
#   - ./recipe.sh
#   - ./rec.sh
#   - ./rec1.sh
   - ./rec2.sh
#   - ./build.sh
   - popd
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"

notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients:
      - lmekala@tibco.com
