language : go 

before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc" 


install:
  - go get github.com/constabulary/gb/...
  - go get -u github.com/constabulary/gb/...
  - go get github.com/TIBCOSoftware/mashling/...
#  - pwd
  - cd ../../TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-recipes.git
  - git clone -b testbin https://github.com/LakshmiMekala/recip1.git
  - pushd recip1/samples-recipes
#  - rm -rf builds/latest
  - mkdir -p master-builds/latest #builds/latest
  - ls
  
script:
   - chmod ugo+x ./common.sh ./final-v14-7.sh
   - ./final-v14-7.sh
   - popd
after_script:
  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"

notifications: 
  email: 
    on_failure: always
    on_success: always
    recipients:
      - lmekala@tibco.com